name: BarcodeSelectionSimpleSample
description: Basic sample to show the minimum code needed to use the Barcode Selection API

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=6.12.1 <6.12.2'
  permission_handler: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
