name: BarcodeSelectionSimpleSample
description: Basic sample to show the minimum code needed to use the Barcode Selection API

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=6.18.0 <6.18.1'
  permission_handler: "10.2.0"

flutter:
  uses-material-design: true
