name: BarcodeCaptureSimpleSample
description: Basic sample that uses the camera to read a single barcode.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=6.24.0 <6.24.1'
  permission_handler: "11.3.0"

flutter:
  uses-material-design: true
