name: BarcodeCaptureViewsSample
description: Demonstrates the various ways to best integrate the scanner into the UI of your app.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=6.20.2 <6.20.3'
  permission_handler: "10.2.0"

flutter:
  uses-material-design: true
