name: IdCaptureExtendedSample
description: A more advanced ID Capture setup.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_id:
    '>=6.25.1 <6.25.2'
  scandit_flutter_datacapture_text:
    '>=6.25.1 <6.25.2'
  permission_handler: "11.3.0"
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ic_barcode.png
    - assets/images/ic_mrz.png
    - assets/images/ic_viz.png
