name: BarcodeCaptureSettingsSample
description: Demonstrates how you can adapt the scanner settings best to your needs and experiment with all the options.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=6.21.2 <6.21.3'
  permission_handler: "10.2.0"

flutter:
  uses-material-design: true
