name: matrixscancountsimplesample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=6.21.2 <6.21.3'
  permission_handler: "10.2.0"

flutter:
  uses-material-design: true
