name: BarcodeSelectionSimpleSample
description: Basic sample to show the minimum code needed to use the Barcode Selection API

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    path: ../../../../scandit-flutter-datacapture-barcode
  permission_handler: 11.3.1

flutter:
  uses-material-design: true
