name: TextCaptureSample
description: Uses Text Capture to recognize various kinds of texts in the specific locations in the frame.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_text:
    '>=6.25.2 <6.25.3'
  scandit_flutter_datacapture_parser:
    '>=6.25.2 <6.25.3'
  permission_handler: "11.3.0"

flutter:
  uses-material-design: true
