name: TextCaptureSample
description: Uses Text Capture to recognize various kinds of texts in the specific locations in the frame.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_text:
    '>=6.22.1 <6.22.2'
  scandit_flutter_datacapture_parser:
    '>=6.22.1 <6.22.2'
  permission_handler: "10.2.0"

flutter:
  uses-material-design: true
