name: IdCaptureSimpleSample
description: A basic ID Capture setup to scan front of ID Cards and barcodes from AAMVA documents.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_id:
    '>=6.28.1 <6.28.2'
  scandit_flutter_datacapture_text:
    '>=6.28.1 <6.28.2'
  permission_handler: "11.3.0"
  intl: ^0.18.0

flutter:
  uses-material-design: true
