name: IdCaptureSimpleSample
description: A basic ID Capture setup to scan front of ID Cards and barcodes from AAMVA documents.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_id:
    '>=6.24.0 <6.24.1'
  scandit_flutter_datacapture_text:
    '>=6.24.0 <6.24.1'
  permission_handler: "11.3.0"
  intl: ^0.18.0

flutter:
  uses-material-design: true
