name: RestockingSample
description: This sample showcases how to run restocking workflows. It uses MatrixScan Pick to help the worker to know which items need to be picked to refill the shelf from the backroom.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=8.6.0 <8.6.1'
  permission_handler: 12.0.3

flutter:
  config:
    enable-swift-package-manager: true
  uses-material-design: true

