name: BarcodeSelectionSettingsSample
description: Demonstrates how you can adapt the barcode selection settings best to your needs and experiment with all the options.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=6.24.1 <6.24.2'
  permission_handler: "11.3.0"

flutter:
  uses-material-design: true
